   

version: "3.8"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo  

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

