module.exports.User = require('./user.model')
module.exports.Task = require('./tasks.model')
module.exports.Profession = require('./profession.model')
module.exports.Payment = require('./payment.model')
module.exports.UserBooking = require('./booking.model')